name: DIR Build Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  export-kicad:
    env:
      BASEFILENAME: "DIR"
      FOLDER: "./pcb"
      SCHEMATICFILEEXTENSION: "kicad_sch"
      PCBFILEEXTENSION: "kicad_pcb"
      OUTPUTFOLDER: "./output"
      CONFIGFILEPATH: ".kibot/build.kibot.yaml"
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v4
    
    - name: Prepare output directory
      run: |
        mkdir -p ${{ env.OUTPUTFOLDER }}
        cp -r ${{ env.FOLDER }} ${{ env.OUTPUTFOLDER }}/kicad
        cp ./LICENSE ${{ env.OUTPUTFOLDER }}

    - name: Run KiBOT
      uses: INTI-CMNB/KiBot@v2_dk7
      with:
        config: ${{ env.CONFIGFILEPATH }}
        dir: ${{ env.OUTPUTFOLDER }}
        schema: "${{ env.FOLDER }}/${{ env.BASEFILENAME }}.${{ env.SCHEMATICFILEEXTENSION }}"
        board: "${{ env.FOLDER }}/${{ env.BASEFILENAME }}.${{ env.PCBFILEEXTENSION }}"

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kicad-export
        path: ${{ env.OUTPUTFOLDER }}
        retention-days: 1
